### ISSUE TITLE
build Error

### ISSUE THREAD

**Issue by Aganivi** [xfy520/docs#1]
`node_modules/.pnpm/vue3-seamless-scroll@2.0.1/node_modules/vue3-seamless-scroll/dist/vue3-seamless-scroll.js:223
    return globalThis.window.cancelAnimationFrame || // @ts-ignore
                             ^

TypeError: Cannot read properties of undefined (reading 'cancelAnimationFrame')
    at /Users/agan/vscode/website/node_modules/.pnpm/vue3-seamless-scroll@2.0.1/node_modules/vue3-seamless-scroll/dist/vue3-seamless-scroll.js:223:30
    at /Users/agan/vscode/website/node_modules/.pnpm/vue3-seamless-scroll@2.0.1/node_modules/vue3-seamless-scroll/dist/vue3-seamless-scroll.js:230:4
    at /Users/agan/vscode/website/node_modules/.pnpm/vue3-seamless-scroll@2.0.1/node_modules/vue3-seamless-scroll/dist/vue3-seamless-scroll.js:2:66
    at Object.<anonymous> (/Users/agan/vscode/website/node_modules/.pnpm/vue3-seamless-scroll@2.0.1/node_modules/vue3-seamless-scroll/dist/vue3-seamless-scroll.js:5:3)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.14.0`

**Comment by Aganivi** [comment]
> `node_modules/.pnpm/vue3-seamless-scroll@2.0.1/node_modules/vue3-seamless-scroll/dist/vue3-seamless-scroll.js:223 return globalThis.window.cancelAnimationFrame || // @ts-ignore ^
> 
> TypeError: Cannot read properties of undefined (reading 'cancelAnimationFrame') at /Users/agan/vscode/website/node_modules/.pnpm/vue3-seamless-scroll@2.0.1/node_modules/vue3-seamless-scroll/dist/vue3-seamless-scroll.js:223:30 at /Users/agan/vscode/website/node_modules/.pnpm/vue3-seamless-scroll@2.0.1/node_modules/vue3-seamless-scroll/dist/vue3-seamless-scroll.js:230:4 at /Users/agan/vscode/website/node_modules/.pnpm/vue3-seamless-scroll@2.0.1/node_modules/vue3-seamless-scroll/dist/vue3-seamless-scroll.js:2:66 at Object. (/Users/agan/vscode/website/node_modules/.pnpm/vue3-seamless-scroll@2.0.1/node_modules/vue3-seamless-scroll/dist/vue3-seamless-scroll.js:5:3) at Module._compile (node:internal/modules/cjs/loader:1226:14) at Module._extensions..js (node:internal/modules/cjs/loader:1280:10) at Module.load (node:internal/modules/cjs/loader:1089:32) at Module._load (node:internal/modules/cjs/loader:930:12) at ModuleWrap. (node:internal/modules/esm/translators:169:29) at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
> 
> Node.js v18.14.0`
